---
env:
  browser: true
  commonjs: true
  es2020: true
  node: true
extends:
  - airbnb-base
  - prettier
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
plugins:
  - prettier
  - '@typescript-eslint'
  - 'import'
overrides:
  - files:
      - '**/*.js'
    rules:
      '@typescript-eslint/no-var-requires': "off"
parserOptions:
  ecmaVersion: 11
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
      - ".tsx"
  import/resolver:
    typescript:
      alwaysTryTypes": true
rules:
  # Snake Case is not for JS/TS
  camelcase: 1
  no-underscore-dangle: 1
  no-param-reassign: 1
  global-require: 1
  prettier/prettier:
    - error
    - semi: false
    - printWidth: 120
  max-len:
    - 2
    - code: 120
  require-await:
    - error
  import/extensions:
    - error
    - never
