env:
  browser: true
  commonjs: true
  es2020: true
  node: true
extends:
  - 'eslint:recommended'
  - prettier
  - 'plugin:@typescript-eslint/recommended'
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
plugins:
  - prettier
  - '@typescript-eslint'
root: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: true
  tsconfigRootDir: './'
  ecmaVersion: 11
rules:
  camelcase: 1
  no-underscore-dangle: 1
  no-param-reassign: 1
  global-require: 1
  prettier/prettier:
    - error
    - semi: false
    - printWidth: 120
  max-len:
    - 2
    - code: 120
  "require-await":
    - "error"
  "@typescript-eslint/no-floating-promises":
    - "error"
  "@typescript-eslint/member-ordering":
    - warn
    - default:
        order: alphabetically
        memberTypes:
          - signature
          - public-static-field
          - protected-static-field
          - private-static-field
          - public-decorated-field
          - protected-decorated-field
          - private-decorated-field
          - public-instance-field
          - protected-instance-field
          - private-instance-field
          - public-abstract-field
          - protected-abstract-field
          - public-field
          - protected-field
          - private-field
          - static-field
          - instance-field
          - abstract-field
          - decorated-field
          - field
          - public-constructor
          - protected-constructor
          - private-constructor
          - constructor
          - public-static-get
          - protected-static-get
          - private-static-get
          - public-decorated-get
          - protected-decorated-get
          - private-decorated-get
          - public-instance-get
          - protected-instance-get
          - private-instance-get
          - public-abstract-get
          - protected-abstract-get
          - public-get
          - protected-get
          - private-get
          - static-get
          - instance-get
          - abstract-get
          - decorated-get
          - get
          - public-static-set
          - protected-static-set
          - private-static-set
          - public-decorated-set
          - protected-decorated-set
          - private-decorated-set
          - public-instance-set
          - protected-instance-set
          - private-instance-set
          - public-abstract-set
          - protected-abstract-set
          - public-set
          - protected-set
          - private-set
          - static-set
          - instance-set
          - abstract-set
          - decorated-set
          - set
          - public-static-method
          - protected-static-method
          - private-static-method
          - public-decorated-method
          - protected-decorated-method
          - private-decorated-method
          - public-instance-method
          - protected-instance-method
          - private-instance-method
          - public-abstract-method
          - protected-abstract-method
          - public-method
          - protected-method
          - private-method
          - static-method
          - instance-method
          - abstract-method
          - decorated-method
          - method
