---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: "charts/.*"
        args:
          - --allow-multiple-documents
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.18.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/gherynos/pre-commit-java
    rev: v0.1.0
    hooks:
      - id: cpd
        exclude: ".*/src/test/.*"
      - id: pmd
        exclude: ".*/src/test/.*"
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: forbid-binary
        exclude: ".*.(png|jpg|jpeg)$"
      - id: markdownlint
      - id: shellcheck
        args:
          - -a
          - -x
          - -e
          - SC1072,SC1073
      - id: script-must-have-extension
      - id: script-must-not-have-extension
      - id: shfmt
        args:
          - -l
          - -i
          - "2"
          - -ci
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.0.0-beta.2
    hooks:
      - id: eslint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args:
          - --pattern
          - '^(?!((fix|feature)\/[a-zA-Z0-9\-]+)$).*'
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks-go
    rev: v1.0.1
    hooks:
      - id: checkmake
        include: "^(.*/?Makefile|.*.mk)$"
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: forbid-tabs
        exclude: "^(.*/?Makefile|.*.mk|.*.go)$"
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        exclude: ".*/templates/.*"
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.1
    hooks:
      - id: docker-compose-check
        files: docker-compose.*y[a]{0,1}ml$
      - id: docker-compose-check
        files: "^docker/.*yaml$"
