version: '3'
services:
  postgres:
    image: postgres:9.6.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EDITION_MODULE: dev.js
    entrypoint: bash -c 'tail -f /dev/null'
    container_name: api_test
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - POSTGRES_SERVICE_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - SESSION_SECRET=sextant
      - TOKEN_SECRET=sextant
      - BTP_DEV_USR
      - BTP_DEV_PSW
