

version: '3'
services:
  api-ecs-sfs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EDITION_MODULE: aws_sfs.js
    image: sextant-api-aws-sfs:${ISOLATION_ID}
  api-ecs-sfd:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EDITION_MODULE: aws_sfd.js
    image: sextant-api-aws-sfd:${ISOLATION_ID}
  api-enterprise:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EDITION_MODULE: enterprise.js
    image: sextant-api-enterprise:${ISOLATION_ID}
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EDITION_MODULE: dev.js
    image: sextant-api:${ISOLATION_ID}
