version: '3'
services:
  postgres:
    image: postgres:9.6.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    image: sextant-api-standard:$ISOLATION_ID
#    entrypoint: bash -c 'tail -f /dev/null'
    container_name: api_test
    depends_on:
      - postgres
    environment:
      - LOG_LEVEL=debug
      - POSTGRES_SERVICE_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - SESSION_SECRET=sextant
      - TOKEN_SECRET=sextant
      - BTP_DEV_USR
      - BTP_DEV_PSW
