---
version: '3'
services:
  api-sfs-nometer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EDITION_MODULE: aws_sfs_nometer
        NODE_ENV: development
        NPM_CI_ARGS: "--omit=dev"
    image: sextant-api-aws-sfs-nometer:${ISOLATION_ID}
  api-sfd-nometer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EDITION_MODULE: aws_sfd_nometer
        NODE_ENV: development
        NPM_CI_ARGS: "--omit=dev"
    image: sextant-api-aws-sfd-nometer:${ISOLATION_ID}
  api-enterprise:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EDITION_MODULE: enterprise
        NODE_ENV: enterprise
        NPM_CI_ARGS: "--omit=dev"
    image: sextant-api-enterprise:${ISOLATION_ID}
  api-standard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EDITION_MODULE: enterprise
        NODE_ENV: standard
        NPM_CI_ARGS: "--omit=dev"
    image: sextant-api-standard:${ISOLATION_ID}
  api-premium:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EDITION_MODULE: enterprise
        NODE_ENV: premium
        NPM_CI_ARGS: "--omit=dev"
    image: sextant-api-premium:${ISOLATION_ID}
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EDITION_MODULE: dev
        NODE_ENV: development
        NPM_CI_ARGS: ""
    image: sextant-api:${ISOLATION_ID}
  api-sft:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EDITION_MODULE: sft
        NODE_ENV: development
        NPM_CI_ARGS: "--omit=dev"
    image: sextant-api-sft:${ISOLATION_ID}
  api-community:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EDITION_MODULE: community
        NODE_ENV: community
        NPM_CI_ARGS: "--omit=dev"
    image: sextant-api-community:${ISOLATION_ID}
