# kubetpl:syntax:go-template
---

apiVersion: v1
kind: Service
metadata:
  name: eth-ethstats
  namespace: {{.ethereum.namespace}}
  labels:
    app: eth-ethstats
spec:
  selector:
    app: eth-ethstats
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
