# kubetpl:syntax:go-template
---

apiVersion: v1
kind: Secret
metadata:
  name: eth-ethstats
  namespace: {{.ethereum.namespace}}
  labels:
    app: eth-ethstats
type: Opaque
data:
  # "changeme"
  WS_SECRET: "Y2hhbmdlbWU="
