# kubetpl:syntax:go-template
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: eth-geth
  namespace: {{.ethereum.namespace}}
  labels:
    app: eth-geth
data:
  networkid: {{.ethereum.networkid | quote}}
  genesis.json: {{.ethereum.genesis_data | quote }}

