# kubetpl:syntax:go-template
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{.deployment.namespace}}
  labels:
    app: {{.deployment.name}}-monitoring
    dns: route53
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    name: grafana
  selector:
    app: {{.deployment.name}}-monitoring
---

apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: {{.deployment.namespace}}
  labels:
    app: {{.deployment.name}}-monitoring
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
    name: influxdb
  selector:
    app: {{.deployment.name}}-monitoring
---

apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: {{.deployment.name}}-monitoring
  namespace: {{.deployment.namespace}}
  labels:
    app: {{.deployment.name}}-monitoring
spec:
  selector:
    matchLabels:
      app: {{.deployment.name}}-monitoring
  serviceName: "{{.deployment.name}}-monitoring"
  template:
    metadata:
      labels:
        app: {{.deployment.name}}-monitoring
    spec:
      containers:
      - name: sawtooth-stats-influxdb
        image: {{.sources.imageRepository}}/sawtooth-stats-influxdb:{{.sources.version}}
        ports:
          - containerPort: 8086
            name: influxdb
        resources:
          limits:
            cpu: "100m"
          requests: 
            cpu: "50m"
      - name: sawtooth-stats-grafana
        image: {{.sources.imageRepository}}/sawtooth-stats-grafana:{{.sources.version}}
        ports:
          - containerPort: 3000
            name: grafana
        resources:
          limits:
            cpu: "100m"
          requests: 
            cpu: "50m"
---

