# kubetpl:syntax:go-template
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eth-bootnode-registrar
  namespace: {{.ethereum.namespace}}
  labels:
    app: eth-bootnode-registrar
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: eth-bootnode-registrar
  serviceName: eth-bootnode-registrar
  template:
    metadata:
      labels:
        app: eth-bootnode-registrar
    spec:
      containers:
      - name: bootnode-registrar
        image: {{.ethereum.registrar.image}}
        imagePullPolicy: IfNotPresent
        env:
        - name: BOOTNODE_SERVICE
          value: "eth-bootnode.{{.ethereum.namespace}}.svc.cluster.local"
        ports:
        - containerPort: 9898
