# kubetpl:syntax:go-template
---

apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: {{.sawtooth.networkName}}-monitoring
  namespace: {{.sawtooth.namespace}}
  labels:
    app: {{.sawtooth.networkName}}-monitoring
spec:
  selector:
    matchLabels:
      app: {{.sawtooth.networkName}}-monitoring
  serviceName: "{{.sawtooth.networkName}}-monitoring"
  template:
    metadata:
      labels:
        app: {{.sawtooth.networkName}}-monitoring
    spec:
      {{ if .imagePullSecrets }}
      imagePullSecrets: 
      {{range .imagePullSecrets.value }}
        - name: {{ . }}
      {{ end }}
      {{ end }}
      containers:
      - name: influxdb
        image: {{.images.influxdb}}
        ports:
          - containerPort: 8086
            name: influxdb
        resources:
          limits:
            cpu: "100m"
          requests: 
            cpu: "50m"
      - name: grafana
        image: {{.images.grafana}}
        ports:
          - containerPort: 3000
            name: grafana
        resources:
          limits:
            cpu: "100m"
          requests: 
            cpu: "50m"
---

