# kubetpl:syntax:go-template
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.sawtooth.networkName}}-sa
  namespace: {{.sawtooth.namespace}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{.sawtooth.networkName}}-role
  namespace: {{.sawtooth.namespace}}
rules:
  - apiGroups: ["","apps/v1"] # "" refers to the core API group
    resources: ["services", "statefulsets.apps","endpoints", "nodes", "pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.sawtooth.networkName}}-clusterrole
  namespace: {{.sawtooth.namespace}}
rules:
  - apiGroups: ["","apps/v1"] # "" refers to the core API group
    resources: ["statefulsets.apps", "nodes",]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{.sawtooth.networkName}}-rb
  namespace: {{.sawtooth.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{.sawtooth.networkName}}-role
subjects:
- kind: ServiceAccount
  name: {{.sawtooth.networkName}}-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{.sawtooth.networkName}}-crb
  namespace: {{.sawtooth.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.sawtooth.networkName}}-clusterrole
subjects:
- kind: ServiceAccount
  name: {{.sawtooth.networkName}}-sa
  namespace: default

---
