# kubetpl:syntax:go-template
---
{{$peering:= .sawtooth.dynamicPeering}}
apiVersion: v1
kind: Service
metadata:
  name: {{.sawtooth.networkName}}-rest-api
  namespace: {{.sawtooth.namespace}}
  labels:
    app: {{.sawtooth.networkName}}-validator
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 8008
    protocol: TCP 
    targetPort: 8008
    name: rest-api
{{ if .sawtooth.seth.enabled }}
  - port: 3030
    protocol: TCP 
    targetPort: 3030
    name: seth-rpc
{{ end }}
  selector:
    app: {{.sawtooth.networkName}}-validator
---

apiVersion: v1
kind: Service
metadata:
  name: {{.sawtooth.networkName}}-validator
  namespace: {{.sawtooth.namespace}}
  labels:
    app: {{.sawtooth.networkName}}-validator
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8800
    protocol: TCP 
    targetPort: 8800
    name: sawnet
  selector:
    app: {{.sawtooth.networkName}}-validator
---

{{ if .sawtooth.xo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{.sawtooth.networkName}}-xo-demo
  namespace: {{.sawtooth.namespace}}
  labels:
    app: {{.sawtooth.networkName}}-xo-demo
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 80
    protocol: TCP 
    targetPort: 80
    name: xo-demo
  selector:
    app: {{.sawtooth.networkName}}-validator
---
{{ end }}