apiVersion: v1
kind: Secret
metadata:
  name: postgressecret
type: Opaque
stringData:
  username: postgres
  password: postgres
  host: daml-on-aurora-test.cluster-cxa50lrjqiri.us-east-2.rds.amazonaws.com
  database: postgres
  port: "5432"
